### ISSUE TITLE
为啥你能做到经常更新

### ISSUE THREAD

**Issue by Soo-For** [xinyanwa/weiwei-xiaotu#1]
= . =

**Comment by xinyanwa** [comment]
每天写一点点😂😂😂

**Comment by Soo-For** [comment]
> 每天写一点点😂😂😂

页面效果挺好的。还用的vue3的框架，厉害厉害。
后期你可以再研究下nuxt的ssr模式，现在官网大多数都要seo优化。

**Comment by Soo-For** [comment]
![image](https://user-images.githubusercontent.com/66558137/146106722-4a035f64-6fe0-42b5-ae21-9860d190c2cb.png)
清理定时器这样比较严谨

**Comment by xinyanwa** [comment]
好滴，这就去更改。不过你说的那个优化我不是很了解。

**Comment by xinyanwa** [comment]
加个微信？嘿嘿，请大佬指教一下

**Comment by Soo-For** [comment]
> 好滴，这就去更改。不过你说的那个优化我不是很了解。

seo就是增加官网在搜索引擎中的曝光率,让搜索排名更靠前。[vue-cli是为单页面应用 (SPA) 快速搭建繁杂的脚手架](https://v3.cn.vuejs.org/guide/installation.html#%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7-cli)。
spa跟ssr的差别可以看下这篇文章[浅谈SPA、SEO、SSR](https://www.jianshu.com/p/fcb98533bc18)

我也是个小菜鸟，也天天各种没见过的需求折磨着~~
